### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by www338** [Conastin/-#1]
这是咋回事啊
<img width="399" alt="image" src="https://user-images.githubusercontent.com/59461656/82626639-e6979d00-9c1a-11ea-85f3-7f17d4a62954.png">

**Comment by Conastin** [comment]
打开主页-打开一门课程的
![image](https://user-images.githubusercontent.com/37993820/84567795-950fa780-adad-11ea-81b3-840a188103b2.png)打开一门课程的
![image](https://user-images.githubusercontent.com/37993820/84567802-a062d300-adad-11ea-916d-5d76473c9eec.png)，再F12刷新拿
![image](https://user-images.githubusercontent.com/37993820/84567809-bc667480-adad-11ea-8f0c-6911d2ab2dd9.png)这个的cookie，使用这个cookie

**Comment by www338** [comment]
> 打开主页-打开一门课程的
> ![image](https://user-images.githubusercontent.com/37993820/84567795-950fa780-adad-11ea-81b3-840a188103b2.png)打开一门课程的
> ![image](https://user-images.githubusercontent.com/37993820/84567802-a062d300-adad-11ea-916d-5d76473c9eec.png)，再F12刷新拿
> ![image](https://user-images.githubusercontent.com/37993820/84567809-bc667480-adad-11ea-8f0c-6911d2ab2dd9.png)这个的cookie，使用这个cookie

不行啊，运行之后显示未登录

**Comment by www338** [comment]
> 打开主页-打开一门课程的
> ![image](https://user-images.githubusercontent.com/37993820/84567795-950fa780-adad-11ea-81b3-840a188103b2.png)打开一门课程的
> ![image](https://user-images.githubusercontent.com/37993820/84567802-a062d300-adad-11ea-916d-5d76473c9eec.png)，再F12刷新拿
> ![image](https://user-images.githubusercontent.com/37993820/84567809-bc667480-adad-11ea-8f0c-6911d2ab2dd9.png)这个的cookie，使用这个cookie

大佬，能不能加个好友啊

**Comment by Conastin** [comment]
你重新clone一下 我更了第二版，教程在首页也有
